import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/navbar/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import { PokeDbProvider } from "@/layout/poke-db/context/PokeDbContext";
import PokeDbLoader from "@/layout/poke-db/components/PokeDbLoader";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
   modal,
}: Readonly<{
   children: React.ReactNode;
   modal: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
               rel="preconnect"
               href="https://fonts.gstatic.com"
               crossOrigin="anonymous"
            />
            <link
               rel="stylesheet"
               href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
            />
         </head>
         <ThemeProvider>
            <PokeDbProvider>
               <PokeDbLoader />
               <body className="px-5 lg:px-30">
                  <main>
                     <Navbar />
                     {children}
                  </main>
                  {modal}
               </body>
            </PokeDbProvider>
         </ThemeProvider>
      </html>
   );
}
