import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/features/navbar/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import { PokeDbProvider } from "@/features/poke-db/context/PokeDbContext";
import PokeDbLoader from "@/features/poke-db/components/PokeDbLoader";
import Pokedex from "@/features/pokedex/components/Pokedex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
        />
      </head>
      <body>
        <ThemeProvider>
          <PokeDbProvider>
            <PokeDbLoader />
            <main className="px-5 lg:px-20">
              <Navbar />
              <div className="w-full flex gap-5 pt-5">
                <Pokedex />
                {children}
              </div>
            </main>
          </PokeDbProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
